auth_app/urls.py
from django.urls import path

from . import views

app_name = "auth"
urlpatterns = [
    path('', views.index, name='index'),
    path("sign-in/", views.sign_in_view, name="sign-in"),
    path("sign-in/processing/", views.sign_in_processing_view, name="sign-in-processing"),
    path("sign-up/", views.sign_up_view, name="sign-up"),
    path("sign-up/processing", views.sign_up_processing_view, name="sign-up-processing"),
    path("sign-out/", views.sign_out_view, name="sign-out"),
]

fastqueue/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("queue_app.urls")),
    path("auth/", include("auth_app.urls")),
    path("admin/", admin.site.urls),
]

queue_app/urls.py
from django.urls import path

from . import views

app_name = "queue"
urlpatterns = [
    path("", views.index, name="index"),
    path("queue/create/", views.queue_create_view, name="queue_create"),
    path("queue/<int:queue_id>/password_processing", views.queue_password_processing, name="queue_password_processing"),
    path("queue/<int:queue_id>/", views.queue_page_view, name="queue_page"),
    path("queue/<int:queue_id>/join", views.queue_page_view_join, name="queue_page_join"),
    path("queue/<int:queue_id>/next/", views.queue_page_view_next, name="queue_page_next"),
    path("queue/<int:queue_id>/clear/", views.queue_page_view_clear, name="queue_page_clear"),
    path("queue/<int:queue_id>/delete/", views.queue_page_view_delete, name="queue_page_delete"),
    path("queue/<int:queue_id>/exit/", views.queue_page_view_exit, name="queue_page_exit"),
]

queue_app/models.py
import uuid

from django.contrib.auth import get_user_model
from django.db import models

from auth_app.models import CustomUser

User = get_user_model()


class Queue(models.Model):
    name = models.CharField(max_length=255)
    keyword = models.SlugField(unique=True, default=uuid.uuid4, editable=False)
    password = models.CharField(max_length=128, blank=True, null=True)

    owner = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='owned_queues')
    participants = models.ManyToManyField(User, through='QueueParticipant', related_name='queues')

    current_index = models.IntegerField(default=0)

    created_at = models.DateTimeField(auto_now_add=True)
    closed_at = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.name

    def add_user_to_queue(self, user):
        """Добавить пользователя в конец очереди"""
        last_position = QueueParticipant.objects.filter(queue=self).count()
        QueueParticipant.objects.create(queue=self, user=user, position=last_position + 1)

    def find_user_in_queue(self, user):
        """Найти id пользователя в очререди"""
        if QueueParticipant.objects.filter(queue=self, user=user).exists():
            return QueueParticipant.objects.filter(queue=self, user=user).first().position
        return -1

    def move_point(self):
        """Передвинуть очередь — сдвинуть всех участников"""
        participants = QueueParticipant.objects.filter(queue=self).order_by('position')
        for qp in participants:
            qp.position -= 1
            qp.save()
        QueueParticipant.objects.filter(queue=self, position__lte=0).delete()

    def clear_queue(self):
        """Очистить очередь"""
        QueueParticipant.objects.filter(queue=self).delete()

    def remove_user_from_queue(self, user):
        """Удаляет пользователя из очереди и пересчитывает позиции"""
        participant = QueueParticipant.objects.filter(queue=self, user=user).first()
        if not participant:
            return False

        participant.delete()

        remaining_participants = QueueParticipant.objects.filter(queue=self).order_by('position')
        for index, p in enumerate(remaining_participants, start=1):
            p.position = index
            p.save()

        return True

    def get_ordered_participants(self):
        return QueueParticipant.objects.filter(queue=self).order_by('position')


class QueueParticipant(models.Model):
    queue = models.ForeignKey(Queue, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    position = models.PositiveIntegerField()

    class Meta:
        unique_together = ('queue', 'user')
        ordering = ['position']

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name} в {self.queue.name} (#{self.position})"

queue_app/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from .models import Queue


@login_required(login_url="auth:sign-in")
def index(request):
    query = request.GET.get('search_request', '')
    if query:
        queues = Queue.objects.filter(keyword__icontains=query)
    else:
        queues = Queue.objects.all()
    return render(
        request,
        'queue_app/queue_search_page.html',
        {
            'user': request.user,
            'queues': queues,
            'search_request': query if query else None,
        })


@login_required(login_url="auth:sign-in")
def queue_create_view(request):
    if request.method == 'POST':
        return queue_create_view_post(request)
    return render(
        request,
        "queue_app/queue_create.html",
        {
            'user': request.user,
        }
    )

def queue_create_view_post(request):
    name = request.POST.get('queue_name')
    keyword = request.POST.get('queue_keyword')
    is_private = request.POST.get('queue_private')
    password = request.POST.get('queue_password')

    if not name or not keyword:
        messages.error(request, "Имя и ключевое слово не могут быть пустыми.")
        return redirect("queue:queue_create")
    if is_private and not password:
        messages.error(request, "Вы указали очередь как приватную, однако не указали пароль.")
        return redirect("queue:queue_create")

    if Queue.objects.filter(keyword=keyword).exists():
        messages.error(request, "Очередь с таким ключевым словом уже есть. Придумайте другое ключевое слово.")
        return redirect("queue:queue_create")

    created_queue = Queue.objects.create(
        name=name,
        keyword=keyword,
        password=password if password else None,
        owner=request.user,
    )

    if not created_queue:
        messages.error(request, "Очередь не была создана.")
        return redirect("queue:queue_create")

    return redirect("queue:queue_page", created_queue.id)

@login_required(login_url="auth:sign-in")
def queue_password_processing(request, queue_id):
    if request.method != 'POST':
        return redirect("queue:index")
    queue = Queue.objects.get(id=queue_id)
    if queue.password != request.POST.get('queue_password'):
        messages.error(request, "Неправильный пароль.")
        return redirect("queue:queue_page_join", queue_id)
    queue.add_user_to_queue(request.user)
    return redirect("queue:queue_page", queue_id)

@login_required(login_url="auth:sign-in")
def queue_page_view_join(request, queue_id):
    queue = Queue.objects.filter(id=queue_id)
    if not queue.exists():
        return render(
            request,
            "queue_app/queue_404.html",
            {
                'user': request.user,
            }
        )
    queue = queue.first()
    if request.user == queue.owner or queue.find_user_in_queue(request.user) != -1:
        return redirect("queue:queue_page", queue_id)
    if queue.password:
        return render(
            request,
            'queue_app/queue_password_enter.html',
            {
                'user': request.user,
                'queue': queue,
            }
        )
    queue.add_user_to_queue(request.user)
    return redirect("queue:queue_page", queue_id)

@login_required(login_url="auth:sign-in")
def queue_page_view(request, queue_id):
    queue = Queue.objects.filter(id=queue_id)
    if not queue.exists():
        return render(
            request,
            "queue_app/queue_404.html",
            {
                'user': request.user,
            }
        )
    queue = queue.first()
    if request.user != queue.owner and queue.find_user_in_queue(request.user) == -1:
        return redirect("queue:index")
    else:
        return render(
            request,
            'queue_app/queue.html',
            {
                'user': request.user,
                'queue': queue,
            }
        )


@login_required(login_url="auth:sign-in")
def queue_page_view_next(request, queue_id):
    queue = Queue.objects.get(id=queue_id)
    if queue is not None and request.user == queue.owner:
        queue.move_point()
    return redirect("queue:queue_page", queue_id)


@login_required(login_url="auth:sign-in")
def queue_page_view_clear(request, queue_id):
    queue = Queue.objects.get(id=queue_id)
    if queue is not None and request.user == queue.owner:
        queue.clear_queue()
    return redirect("queue:queue_page", queue_id)


@login_required(login_url="auth:sign-in")
def queue_page_view_delete(request, queue_id):
    queue = Queue.objects.get(id=queue_id)
    if queue is not None and request.user == queue.owner:
        queue.delete()
    return redirect("queue:index")


@login_required(login_url="auth:sign-in")
def queue_page_view_exit(request, queue_id):
    queue = Queue.objects.filter(id=queue_id).first()
    if queue and queue.find_user_in_queue(request.user) != -1:
        queue.remove_user_from_queue(request.user)
        return redirect("queue:index")
    return redirect("queue:queue_page", queue_id=queue_id)

queue_app/templates/queue_app/queue.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Очередь {{ queue.name }}</title>
    <link rel="stylesheet" href="{% static 'queue_app/queue_page_style.css' %}">
</head>
<body>
    <div class="main">
        <div class="user_info">
            <p>Вы вошли как {{ user.first_name }} {{ user.last_name }}</p>
            <a href="{% url 'auth:sign-out' %}">Выйти из аккаунта</a>
        </div>
        <a href="{% url 'queue:index' %}">Вернуться домой</a>
        <div class="queue_block">
            <div class="queue_info">
                <div class="queue_info_content">
                    <div class="queue_name">
                        <h4>Очередь</h4>
                        <h1>{{ queue.name }}</h1>
                    </div>
                    <p>Ключевое слово: <strong>{{ queue.keyword }}</strong></p>
                    {% if queue.password is None %}
                        <p>Очередь является <strong>публичной</strong>.
                            Каждый пользователь FastQueue может войти в вашу очередь.</p>
                    {% else %}
                        <p>Очередь является <strong>приватной</strong>.
                            Для входа в очередь пользователям необходимо ввести пароль.</p>
                    {% endif %}
                    {% if queue.owner == user and queue.password is not None %}
                        <p class="password_block">Пароль для входа:
                            <strong id="password">{{ queue.password }}</strong>
                            <button id="show_password_btn">Показать пароль</button>
                        </p>
                    {% endif %}
                </div>
            </div>
            <div class="queue_list">
                <div class="queue_list_content">
                    <h2>Люди в очереди</h2>
                    <div class="queue-grid">
                        <div class="grid-header">№</div>
                        <div class="grid-header">Имя и фамилия</div>
                        {% for qp in queue.get_ordered_participants %}
                            <div class="grid-item">{{ qp.position }}</div>
                            <div class="grid-item">{{ qp.user.first_name }} {{ qp.user.last_name }}</div>
                        {% empty %}
                            <div class="grid-item" style="grid-column: span 2;">Очередь пуста</div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <div class="control-panel">
            {% if user == queue.owner %}
                <a href="{% url 'queue:queue_page_next' queue.id %}"
                   class="control-panel-btn next-btn">Следующий</a>
                <a href="{% url 'queue:queue_page_clear' queue.id %}"
                   class="control-panel-btn clear-btn">Очистить очередь</a>
                <a href="{% url 'queue:queue_page_delete' queue.id %}"
                   class="control-panel-btn delete-btn">Удалить очередь</a>
            {% else %}
                <a href="{% url 'queue:queue_page_exit' queue.id %}"
                   class="control-panel-btn exit-btn">Выйти из очереди</a>
            {% endif %}
        </div>
    </div>
    {% if user == queue.owner %}
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            let password_btn = document.getElementById("show_password_btn");
            let password_text = document.getElementById('password');

            password_text.style.display = (password_btn.innerText === "Показать пароль") ? 'none' : 'block'

            password_btn.innerText = "Показать пароль";

            password_btn.addEventListener('click', () => {
                password_btn.innerText = (password_btn.innerText === "Показать пароль") ? 'Скрыть пароль' : 'Показать пароль'
                password_text.style.display = (password_btn.innerText === "Показать пароль") ? 'none' : 'block'
            })
        });
    </script>
    {% endif %}
</body>
</html>

queue_app/templates/queue_app/queue_404.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ошибка 404</title>
    <link rel="stylesheet" href="{% static 'queue_app/queue_search_style.css' %}">
</head>
<body>
    <div class="main">
        <div class="user_info">
            <p>Вы вошли как {{ user.first_name }} {{ user.last_name }}</p>
            <a href="{% url 'auth:sign-out' %}">Выйти из аккаунта</a>
        </div>
        <div class="search_block">
            <h1>Упс...</h1>
            <p>Походу вы заблудились :/</p>
            <a href="{% url 'queue:index' %}">Вернуться на главную</a>
        </div>
    </div>
</body>
</html>

queue_app/templates/queue_app/queue_create.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Создание очереди</title>
    <link rel="stylesheet" href="{% static 'queue_app/queue_create_style.css' %}">
</head>
<body>
    <div class="main">
        <div class="user_info">
            <p>Вы вошли как {{ user.first_name }} {{ user.last_name }}</p>
            <a href="{% url 'auth:sign-out' %}">Выйти из аккаунта</a>
        </div>
        <a href="{% url 'queue:index' %}">Вернуться домой</a>
        <div class="create_block">
            <h1>Создание очереди</h1>
            {% if messages %}
            <ul class="container__messages">
            {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
            {% endif %}
            </ul>
            <form id="create_form" method="post" action="{% url 'queue:queue_create' %}">
                {% csrf_token %}
                <div class="form-group">
                    <label class="title">Название очереди</label>
                    <input class="form-control" name="queue_name" type="text" placeholder="Введите название очереди..." required>
                </div>
                <div class="form-group">
                    <label class="title">Ключевое слово</label>
                    <input class="form-control" name="queue_keyword" type="text" placeholder="Введите ключевое слово..." required>
                </div>
                <div class="form-group">
                    <label class="title">Приватность</label>
                    <label class="switch">
                        <input name="queue_private" type="checkbox" id="private-flag">
                        <span class="slider"></span>
                    </label>
                </div>
                <div id="private-password" class="form-group">
                    <label class="title">Пароль</label>
                    <input class="form-control" name="queue_password" type="password" placeholder="Введите пароль...">
                </div>
                <button type="submit">Войти в очередь</button>
            </form>
        </div>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const form = document.getElementById('create_form');
            const privateFlag = document.getElementById('private-flag');
            const privatePasswordInput = document.getElementById('private-password');

            privatePasswordInput.style.display = privateFlag.checked ? 'flex' : 'none';

            privateFlag.addEventListener('change', function() {
                privatePasswordInput.style.display = privateFlag.checked ? 'flex' : 'none';
            });
        });
    </script>
</body>
</html>

queue_app/templates/queue_app/queue_password_enter.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Поиск очереди</title>
    <link rel="stylesheet" href="{% static 'queue_app/queue_password_enter_style.css' %}">
</head>
<body>
    <div class="main">
        <div class="user_info">
            <p>Вы вошли как {{ user.first_name }} {{ user.last_name }}</p>
            <a href="{% url 'auth:sign-out' %}">Выйти из аккаунта</a>
        </div>
        <a href="{% url 'queue:index' %}">Вернуться домой</a>
        <div class="search_block">
            <h1>Введите пароль</h1>
            <p>Очередь "{{ queue.name }}" является приватным. Введите пароль, который предоставил создатель очереди.</p>
            {% if messages %}
            <ul class="container__messages">
            {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
            </ul>
            {% endif %}
            <form method="post" action="{% url 'queue:queue_password_processing' queue.id %}">
                {% csrf_token %}
                <input name="queue_password" type="password" placeholder="Пароль для входа в очередь...">
                <button type="submit">Войти в очередь</button>
            </form>
        </div>
    </div>
</body>
</html>

queue_app/templates/queue_app/queue_search.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Поиск очереди</title>
    <link rel="stylesheet" href="{% static 'queue_app/queue_style.css' %}">
</head>
<body>
    <div class="main">
        <div class="user_info">
            <p>Вы вошли как {{ user.first_name }} {{ user.last_name }}</p>
            <a href="{% url 'auth:sign-out' %}">Выйти из аккаунта</a>
        </div>
        <div class="search_block">
            <h1>Поиск очереди</h1>
            <form method="get" action="{% url 'queue:index' %}">
                {% csrf_token %}
                <input name="search_request" type="search" placeholder="Поиск очереди по ключевому слову...">
                <button type="submit">Найти</button>
            </form>
        </div>
        <div class="queues_block">
            <h2>{% if search_request is None %}Ваши очереди
            {% else %}Результат по запросу <strong>{{ search_request }}</strong>{% endif %}</h2>
            <div class="queues_grid">
                {% if search_request is None %}
                <a class="create_card" href="#">
                    <h3>Создать очередь</h3>
                </a>
                {% endif %}
                {% if queues.count == 0 and search_request is not None %}
                    <p>По вашему запросу ничего не было найдено :(</p>
                {% endif %}
                {% for queue in queues %}
                    <div class="queue_card">
                        <div class="queue_card_content">
                            <h3>{{ queue.name }}</h3>
                            <p class="code_word">Кодовое слово: {{ queue.keyword }}</p>
                            <p class="num_of_people">Кол-во людей: {{ queue.participants.count }}</p>
                            <a href="{% url 'queue:queue_page' queue.id %}">Войти в очередь</a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</body>
</html>

queue_app/templates/queue_app/queue_search_page.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Поиск очереди</title>
    <link rel="stylesheet" href="{% static 'queue_app/queue_search_style.css' %}">
</head>
<body>
    <div class="main">
        <div class="user_info">
            <p>Вы вошли как {{ user.first_name }} {{ user.last_name }}</p>
            <a href="{% url 'auth:sign-out' %}">Выйти из аккаунта</a>
        </div>
        <div class="search_block">
            <h1>Поиск очереди</h1>
            <form method="get" action="{% url 'queue:index' %}">
                {% csrf_token %}
                <input name="search_request" type="search" placeholder="Поиск очереди по ключевому слову...">
                <button type="submit">Найти</button>
            </form>
        </div>
        <div class="queues_block">
            <h2>{% if search_request is None %}Ваши очереди
            {% else %}Результат по запросу <strong>{{ search_request }}</strong>{% endif %}</h2>
            <div class="queues_grid">
                {% if search_request is None %}
                <a class="create_card" href="{% url 'queue:queue_create' %}">
                    <h3>Создать очередь</h3>
                </a>
                {% endif %}
                {% if queues.count == 0 and search_request is not None %}
                    <p>По вашему запросу ничего не было найдено :(</p>
                {% endif %}
                {% for queue in queues %}
                    <div class="queue_card">
                        <div class="queue_card_content">
                            <h3>{{ queue.name }}</h3>
                            <p class="code_word">Кодовое слово: {{ queue.keyword }}</p>
                            <p class="num_of_people">Кол-во людей: {{ queue.participants.count }}</p>
                            <a href="{% url 'queue:queue_page_join' queue.id %}">Войти в очередь</a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</body>
</html>