auth_app/urls.py
from django.urls import path

from . import views

app_name = "auth"
urlpatterns = [
    path('', views.index, name='index'),
    path("sign-in/", views.sign_in_view, name="sign-in"),
    path("sign-in/processing/", views.sign_in_processing_view, name="sign-in-processing"),
    path("sign-up/", views.sign_up_view, name="sign-up"),
    path("sign-up/processing", views.sign_up_processing_view, name="sign-up-processing"),
    path("sign-out/", views.sign_out_view, name="sign-out"),
]

fastqueue/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("queue_app.urls")),
    path("auth/", include("auth_app.urls")),
    path("admin/", admin.site.urls),
]

auth_app/models.py
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager,
                                        PermissionsMixin)
from django.db import models
from django.utils import timezone


class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("Email обязателен")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if not extra_fields.get('is_staff'):
            raise ValueError("Суперпользователь должен иметь is_staff=True.")
        if not extra_fields.get('is_superuser'):
            raise ValueError("Суперпользователь должен иметь is_superuser=True.")

        return self.create_user(email, password, **extra_fields)


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True, verbose_name="Электронная почта")
    first_name = models.CharField(max_length=30, verbose_name="Имя")
    last_name = models.CharField(max_length=30, verbose_name="Фамилия")
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(default=timezone.now)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    def __str__(self):
        return self.email

auth_app/forms.py
from django import forms
from django.contrib.auth import authenticate

from . import models


class SignInForm(forms.Form):
    email = forms.EmailField(label="Email")
    password = forms.CharField(widget=forms.PasswordInput, label="Пароль")

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get('email')
        password = cleaned_data.get('password')
        user = authenticate(email=email, password=password)
        if not user:
            raise forms.ValidationError('Неправильный email или пароль.')
        cleaned_data["user"] = user
        return cleaned_data


class SignUpForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput, label="Пароль")
    confirm_password = forms.CharField(widget=forms.PasswordInput, label="Подтверждение пароля")

    class Meta:
        model = models.CustomUser
        fields = ['first_name', 'last_name', 'email', 'password', 'confirm_password']

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password and confirm_password and password != confirm_password:
            raise forms.ValidationError("Пароли не совпадают.")

        return cleaned_data

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if models.CustomUser.objects.filter(email=email).exists():
            raise forms.ValidationError("Пользователь с таким адресом электронной почты уже существует.")
        return email

auth_app/views.py
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from . import forms

REDIRECT_URL = "queue:index"


def index(request):
    if request.user.is_authenticated:
        return redirect(REDIRECT_URL)
    return redirect("auth:sign-in")


def sign_in_view(request):
    if request.user.is_authenticated:
        return redirect(REDIRECT_URL)
    form = forms.SignInForm()
    return render(
        request,
        "auth_app/sign_in.html",
        {
            "form": form,
        })


def sign_in_processing_view(request):
    if request.method == "POST":
        form = forms.SignInForm(request.POST)
        if form.is_valid():
            user = form.cleaned_data["user"]
            login(request, user)
            return redirect(REDIRECT_URL)
        messages.error(request, "Неправильный email или пароль.")
        return redirect("auth:sign-in")
    messages.error(request, "Что-то пошло не так.")
    return redirect("auth:sign-in")


def sign_up_view(request):
    if request.user.is_authenticated:
        return redirect(REDIRECT_URL)
    form = forms.SignUpForm()
    return render(
        request,
        "auth_app/sign_up.html",
        {
            "form": form
        })


def sign_up_processing_view(request):
    if request.method == "POST":
        form = forms.SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data["password"])
            user.save()
            login(request, user)
            return redirect(REDIRECT_URL)
        else:
            messages.error(request, "Пользователь с таким email уже существует или был введен простой пароль.")
            return redirect("auth:sign-up")
    messages.error(request, "Что-то пошло не так.")
    return redirect("auth:sign-up")


@login_required(login_url="auth:sign-in")
def sign_out_view(request):
    logout(request)
    return redirect("auth:sign-in")

auth_app/templates/auth_app/sign_in.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Вход</title>
    <link rel="stylesheet" href="{% static 'auth_app/style.css' %}">
</head>
<body>
    <div class="container">
        <h2 class="container__header">Вход</h2>
        {% if messages %}
            <ul class="container__messages">
            {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
            </ul>
        {% endif %}
        <form class="container__form" method="post" action="{% url 'auth:sign-in-processing' %}">
            {% csrf_token %}
            {{ form.as_div }}
            <button type="submit">Войти</button>
        </form>
        <p>У вас нет аккаунта? <a href="{% url 'auth:sign-up' %}">Зарегистрироваться</a></p>
    </div>
</body>
</html>

auth_app/templates/auth_app/sign_up.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Регистрация</title>
    <link rel="stylesheet" href="{% static 'auth_app/style.css' %}">
</head>
<body>
    <div class="container">
        <h2 class="container__header">Регистрация</h2>
        {% if messages %}
            <ul class="container__messages">
            {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
            </ul>
        {% endif %}
        <form class="container__form" method="post" action="{% url 'auth:sign-up-processing' %}">
            {% csrf_token %}
            {{ form.as_div }}
            <button type="submit">Зарегистрироваться</button>
        </form>
        <p>У вас уже есть аккаунта? <a href="{% url 'auth:sign-in' %}">Войти</a></p>
    </div>
</body>
</html>